version: '3.7'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - engine

  engine:
    build: ./engine
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
    tty: true

volumes:
  es-data:
